project:
  type: website

website:
  title: "Know More Names"
  navbar:
    left:
      - href: fatal_encounters.qmd
        text: Fatal Encounters
      - href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



