---
title: "About"
---
```{=html}
<div class="about-info">
```
# Purpose
This web application aims to serve community members, activists, and lawmakers by inter-linking existing datasets and rich unstructured data sources to make the information more easily accessible and contextualized. 

# Datasets and data structure: 
This web application leverages the following datasets: Wikidata knowledge graph (see KSR’s WikiProject [here](https://www.wikidata.org/wiki/Wikidata:WikiProject_Systemic_Racism_Knowledge_Graph)) and additional data to be completed (*):  
```{=html}
<ol>
    <li>Black people killed during encounters with the police in California </li>
    <li>Event of those encounters</li>
    <li>California law enforcement agencies (LEAs)</li>
    <li>Military equipment index and taxonomy including images*</li>
    <li>Key legal terms in policies and extracted (words in context) from LEA policy documents*</li>
    <li>Military equipment inventories* </li>
</ol>
```

# How it works
### Updating data to reflect Wikidata/other data source's changes
A scheduled GitHub Actions workflow runs every month to dynamically update the information on this website if there have been any changes to the data sources. 

### Data flow
The data in the information cards for the Fatal Encounters and Law Enforcement Agency sections is pulled directly from Wikidata using their API. For now, the data for the other sections on the website have not yet been entered into Wikidata, so they are being pulled from Google Sheets using Python's Pandas library. 

# Open source
Check out this website's repository [here](https://github.com/know-systemic-racism/know-more-names-app-final). 
```{=html}
</div>
```